services:
  frontend:
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - ENVOY_PROXY=http://envoy:8080
      - GOOGLE_ID=123123

networks:
  wenjim:
