services:
  frontend:
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - BACKEND_PROXY=http://grpc-backend:8080
      - HOST=http://localhost:3000

networks:
  wenjim:
