version: '3'

services:
  wenjim-backend-staging:
    build: .
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./backend/data:/app/data

  envoy:
    build:
      context: .
      dockerfile: Dockerfile_envoy_staging
    ports:
      - "8080:8080"
    depends_on:
      - wenjim-backend-staging
