version: '3'

services:
  grpc-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data

networks:
  wenjim:
