version: '3'

services:
  grpc-backend:
    build: .
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./backend/data:/app/data

  envoy:
    build:
      context: .
      dockerfile: Dockerfile_envoy
    ports:
      - "8080:8080"
    depends_on:
      - grpc-backend
