version: "1"

services:
  flask-server:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    expose: [ 5000 ]
    env_file:
      - .env.dev

  postgres:
      image: postgres
      env_file:
        - .env.dev
      ports:
        - "5432:5432"
      volumes:
        - ./data/sql:/var/lib/postgresql/data

networks:
  default:
    name: wenjim
