version: "1"

services:
  flask-server:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    expose: [ 5000 ]
    volumes:
      - ./data:/data
    environment:
      - FLASK_DEBUG=true
