name: Test Flake.nix

on: push

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix --experimental-features 'nix-command flakes' develop
